# Generated by Django 2.2.4 on 2019-10-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0014_artifactdescriptor_mandatory'),
        ('proceedings', '0002_rename_volume_assignment_to_camera_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Attachment')),
                ('camera_ready', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proceedings.CameraReady')),
                ('descriptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferences.ArtifactDescriptor')),
            ],
        ),
    ]
