# Generated by Django 2.2.4 on 2019-10-07 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_remove_descriptor_from_attachment'),
        ('conferences', '0015_artifactdescriptor_editable'),
        ('proceedings', '0005_auto_20191007_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraready',
            name='volume',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferences.ProceedingVolume'),
        ),
        migrations.AlterUniqueTogether(
            name='cameraready',
            unique_together={('submission', 'proc_type')},
        ),
    ]
