# Generated by Django 2.1.7 on 2019-03-31 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import submissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0002_auto_20190329_1326'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Title')),
                ('abstract', models.CharField(default='', max_length=2500, verbose_name='Abstract')),
                ('status', models.CharField(choices=[('SUBMIT', 'Submitted'), ('REVIEW', 'Review'), ('REJECT', 'Rejected'), ('ACCEPT', 'Accepted'), ('PRINT', 'In-print'), ('PUBLISH', 'Published')], default='SUBMIT', max_length=10)),
                ('review_manuscript', models.FileField(blank=True, upload_to=submissions.models.get_review_manuscript_full_path)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferences.Conference')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submissions', to=settings.AUTH_USER_MODEL)),
                ('stype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='conferences.SubmissionType', verbose_name='Submission type')),
                ('topics', models.ManyToManyField(to='conferences.Topic', verbose_name='Topics')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='submissions.Submission'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorship', to=settings.AUTH_USER_MODEL),
        ),
    ]
