# Generated by Django 2.1.7 on 2019-04-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['order']},
        ),
    ]
