# Generated by Django 2.1.7 on 2019-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20190401_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reached_overview',
            field=models.BooleanField(default=False),
        ),
    ]
