# Generated by Django 2.1.7 on 2019-04-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_reached_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='filled_details',
            field=models.BooleanField(default=False),
        ),
    ]
