# Generated by Django 2.2.4 on 2019-08-29 17:36

from django.db import migrations, models
import django.db.models.deletion
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0011_artifactdescriptor'),
        ('submissions', '0004_submission_filled_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=submissions.models.get_artifact_full_path)),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='conferences.ArtifactDescriptor')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='submissions.Submission')),
            ],
        ),
    ]
