# Generated by Django 2.2.4 on 2019-10-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0014_artifactdescriptor_mandatory'),
        ('submissions', '0006_auto_20190905_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artifact',
            new_name='Attachment',
        ),
    ]
