# Generated by Django 2.2.4 on 2019-10-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_rename_artifact_to_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='access',
            field=models.CharField(choices=[('NO', 'Inactive (no access)'), ('RO', 'Read only'), ('RW', 'Read and write')], default='RW', max_length=2),
        ),
        migrations.AddField(
            model_name='attachment',
            name='label',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
