# Generated by Django 2.1.7 on 2019-03-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190326_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name_rus',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='First Name in Russian'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name_rus',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Last Name in Russian'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name_rus',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Middle Name in Russian'),
        ),
    ]
