# Generated by Django 2.1.7 on 2019-03-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190326_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_finished_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City in English'),
        ),
    ]
