# Generated by Django 2.1.7 on 2019-03-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='agree_to_receive_emails',
        ),
    ]
