from django.urls import path

from .views import profile, submissions, conferences


urlpatterns = [
    path('', submissions.user_details, name='submissions'),

    path('profile/overview/', profile.overview_page,
         name='profile-overview'),
    path('profile/account/', profile.account_page,
         name='profile-account'),
    path('profile/personal/', profile.personal_settings,
         name='profile-personal'),
    path('profile/professional/', profile.professional_settings,
         name='profile-professional'),
    path('profile/reviewer/', profile.reviewer_settings,
         name='profile-reviewer'),
    path('profile/update/email/', profile.update_email,
         name='profile-update-email'),
    path('profile/update/subscriptions/', profile.update_subscriptions,
         name='profile-update-subscriptions'),
    path('profile/update/password/', profile.update_password,
         name='profile-update-password'),
    path('profile/update/avatar/', profile.update_avatar,
         name='profile-update-avatar'),
    path('profile/delete/', profile.delete_account,
         name='profile-delete'),
    path('profile/delete/avatar/', profile.delete_avatar,
         name='profile-delete-avatar'),

    path('conferences/', conferences.conferences_list,
         name='conferences-list'),
    path('conferences/new/', conferences.conference_create,
         name='conference-create'),
    path('conferences/<int:pk>/', conferences.conference_details,
         name='conference-details'),
    path('conferences/<int:pk>/settings/', conferences.conference_edit,
         name='conference-edit'),
    path('conferences/<int:pk>/stages/submission',
         conferences.conference_submission_stage,
         name='conference-submission-stage'),
    path('conferences/<int:pk>/stages/reviews',
         conferences.conference_review_stage,
         name='conference-review-stage'),
    path('conferences/<int:pk>/proceedings/new/',
         conferences.proceedings_create,
         name='conference-proceedings-create'),
    path('conferences/<int:pk>/proceedings/<int:proc_pk>/',
         conferences.proceedings_update,
         name='conference-proceedings-update'),
    path('conferences/<int:pk>/proceedings/<int:proc_pk>/delete/',
         conferences.proceedings_delete,
         name='conference-proceedings-delete'),
    path('conferences/<int:pk>/submissiontype/new/',
         conferences.submission_type_create,
         name='conference-submissiontype-create'),
    path('conferences/<int:pk>/submissiontype/<int:sub_pk>/',
         conferences.submission_type_update,
         name='conference-submissiontype-update'),
    path('conferences/<int:pk>/submissiontype/<int:sub_pk>/delete/',
         conferences.submission_type_delete,
         name='conference-submissiontype-delete'),
]
