# Generated by Django 2.1.7 on 2019-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_auto_20190329_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Medium length description of the conference'),
        ),
        migrations.AddField(
            model_name='conference',
            name='site_url',
            field=models.URLField(blank=True, default='', verbose_name='Conference informational site'),
        ),
    ]
