# Generated by Django 2.1.7 on 2019-03-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20190328_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='year',
        ),
    ]
