# Generated by Django 2.1.7 on 2019-03-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20190331_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionstage',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Deadline for submissions'),
        ),
    ]
