# Generated by Django 2.1.7 on 2019-03-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_auto_20190331_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceedingtype',
            name='final_manuscript_deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline for final manuscript submission'),
        ),
        migrations.AlterField(
            model_name='reviewstage',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End of review'),
        ),
    ]
