# Generated by Django 2.1.7 on 2019-03-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_auto_20190328_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='logotype',
            field=models.ImageField(blank=True, null=True, upload_to='public//conferences/logo/', verbose_name='Conference logotype'),
        ),
    ]
