# Generated by Django 2.1.7 on 2019-03-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_conference_logotype'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='blind_review',
            field=models.BooleanField(default=False, verbose_name='Blind review'),
        ),
    ]
