# Generated by Django 2.1.7 on 2019-04-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_auto_20190402_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Topic name'),
        ),
    ]
