# Generated by Django 2.1.9 on 2019-07-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_auto_20190416_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='min_num_words_in_review',
            field=models.IntegerField(default=150, verbose_name='Minimum number of words in the review'),
        ),
    ]
