# Generated by Django 2.1.7 on 2019-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_submissiontype_blind_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceedingtype',
            name='final_latex_template',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='LaTeX template for final manuscript'),
        ),
    ]
