# Generated by Django 2.1.10 on 2019-07-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_submissiontype_min_num_words_in_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
