# Generated by Django 2.1.7 on 2019-03-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_auto_20190328_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceedingtype',
            name='max_num_pages',
            field=models.IntegerField(default=4, verbose_name='Maximum number of pages in submission'),
        ),
        migrations.AddField(
            model_name='proceedingtype',
            name='min_num_pages',
            field=models.IntegerField(default=4, verbose_name='Minimum number of pages in submission'),
        ),
    ]
