# Generated by Django 2.2.4 on 2019-08-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_conference_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceedingVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Short name')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='conferences.ProceedingType')),
            ],
        ),
    ]
