# Generated by Django 2.1.7 on 2019-03-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0010_auto_20190329_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceedingtype',
            name='final_latex_template',
            field=models.FileField(blank=True, null=True, upload_to='public//conferences/templates', verbose_name='LaTeX template for final manuscript'),
        ),
        migrations.AlterField(
            model_name='submissiontype',
            name='latex_template',
            field=models.FileField(null=True, upload_to='public//conferences/templates', verbose_name='LaTeX template'),
        ),
    ]
