# Generated by Django 2.2.4 on 2019-08-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0011_artifactdescriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactdescriptor',
            name='materials_url',
            field=models.URLField(blank=True, default='', verbose_name='Additional materials (templates, forms, etc.)'),
        ),
        migrations.AlterField(
            model_name='artifactdescriptor',
            name='code',
            field=models.CharField(default='FINAL', max_length=8, verbose_name='Alphanumeric code to append to file name'),
        ),
    ]
