# Generated by Django 2.1.7 on 2019-03-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0011_auto_20190329_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceedingtype',
            name='_final_latex_template_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='_latex_template_version',
            field=models.IntegerField(default=1),
        ),
    ]
