# Generated by Django 2.2.4 on 2019-08-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0012_auto_20190829_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactdescriptor',
            name='materials_url',
            field=models.URLField(blank=True, default='', verbose_name='URL with additional materials (templates, forms)'),
        ),
    ]
