# Generated by Django 2.2.4 on 2019-10-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0015_artifactdescriptor_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='')),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactDescriptorLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='conferences.ArtifactDescriptor')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.ExternalFile')),
            ],
            options={
                'unique_together': {('descriptor', 'link')},
            },
        ),
    ]
