# Generated by Django 2.2.4 on 2019-10-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0017_copy_materials_to_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactdescriptor',
            name='materials_url',
        ),
    ]
