# Generated by Django 2.1.10 on 2019-07-17 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_conference_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chair_mail', '0002_auto_20190716_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessageBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('html', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('html', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='htmlemailtemplate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='htmlemailtemplate',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='htmlemailtemplate',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='textemailtemplate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='textemailtemplate',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='textemailtemplate',
            name='created_by',
        ),
        migrations.RenameField(
            model_name='emailgeneralsettings',
            old_name='footer_html',
            new_name='footer',
        ),
        migrations.RenameField(
            model_name='emailgeneralsettings',
            old_name='sign_footer_html',
            new_name='signature',
        ),
        migrations.RemoveField(
            model_name='emailgeneralsettings',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='emailgeneralsettings',
            name='sign_footer_text',
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
        migrations.DeleteModel(
            name='HtmlEmailTemplate',
        ),
        migrations.DeleteModel(
            name='TextEmailTemplate',
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('name', 'conference')},
        ),
        migrations.AlterUniqueTogether(
            name='emailmessagebody',
            unique_together={('name', 'conference')},
        ),
    ]
