# Generated by Django 2.1.10 on 2019-07-17 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_conference_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chair_mail', '0003_auto_20190717_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template_string', models.CharField(max_length=1024)),
                ('html_template_string', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('TX', 'Sending'), ('SENT', 'Sent')], default='DRAFT', max_length=5)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference')),
                ('users_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessageInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=1024)),
                ('text', models.TextField()),
                ('html', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chair_mail.EmailMessage')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='emailmessagebody',
            name='message_type',
            field=models.CharField(default='USER_MESSAGE', max_length=256),
        ),
        migrations.AlterField(
            model_name='emailmessagebody',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailmessagebody',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='emailmessagebody',
            unique_together={('name', 'conference', 'message_type')},
        ),
    ]
