# Generated by Django 2.1.10 on 2019-07-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair_mail', '0004_auto_20190717_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgeneralsettings',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
