# Generated by Django 2.2.4 on 2019-09-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair_mail', '0004_auto_20190828_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnotification',
            name='name',
            field=models.CharField(choices=[('assign_status_review', 'Assign status REVIEW to the paper'), ('assign_status_submit', 'Assign status SUBMIT to the paper'), ('assign_status_accept', 'Assign status ACCEPT to the paper'), ('assign_status_reject', 'Assign status REJECT to the paper'), ('assign_status_inprint', 'Assign status IN-PRINT to the paper'), ('assign_status_publish', 'Assign status PUBLISHED to the paper')], max_length=64),
        ),
    ]
