# Generated by Django 2.1.10 on 2019-07-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chair_mail', '0006_auto_20190718_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailmessagebody',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='emailmessagebody',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='emailmessagebody',
            name='created_by',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='subject_template_string',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='html_template_string',
            new_name='text_html',
        ),
        migrations.RenameField(
            model_name='emailmessageinst',
            old_name='html',
            new_name='text_html',
        ),
        migrations.RenameField(
            model_name='emailmessageinst',
            old_name='text',
            new_name='text_plain',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='html',
            new_name='text_html',
        ),
        migrations.RemoveField(
            model_name='emailgeneralsettings',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='emailgeneralsettings',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='emailgeneralsettings',
            name='signature',
        ),
        migrations.AddField(
            model_name='emailgeneralsettings',
            name='default_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chair_mail.EmailTemplate'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='text_plain',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='text_plain',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='EmailMessageBody',
        ),
    ]
