# Generated by Django 2.1.10 on 2019-07-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_conference_contact_email'),
        ('chair_mail', '0007_auto_20190719_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgeneralsettings',
            name='conference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference'),
        ),
    ]
