# Generated by Django 2.1.10 on 2019-07-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chair_mail', '0008_emailgeneralsettings_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailgeneralsettings',
            name='conference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_settings', to='conferences.Conference'),
        ),
    ]
