# Generated by Django 2.1.10 on 2019-07-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chair_mail', '0009_auto_20190720_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailgeneralsettings',
            old_name='default_template',
            new_name='template',
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='name',
        ),
    ]
