# Generated by Django 2.1.10 on 2019-07-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair_mail', '0010_auto_20190720_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
