# Generated by Django 2.1.10 on 2019-07-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair_mail', '0011_auto_20190722_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessageinst',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
