# Generated by Django 2.1.10 on 2019-07-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair_mail', '0012_auto_20190722_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='message_type',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
