# Generated by Django 2.1.10 on 2019-07-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chair_mail', '0013_emailmessage_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='text_html',
            new_name='body_html',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='text_plain',
            new_name='body_plain',
        ),
    ]
