# Generated by Django 2.1.9 on 2019-07-10 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0007_auto_20190416_1115'),
        ('submissions', '0004_submission_filled_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_merit', models.CharField(blank=True, choices=[('', 'Choose your score'), ('1', '1 - Very Poor'), ('2', '2 - Below Average'), ('3', '3 - Average'), ('4', '4 - Good'), ('5', '5 - Excellent')], max_length=1)),
                ('clarity', models.CharField(blank=True, choices=[('', 'Choose your score'), ('1', '1 - Very Poor'), ('2', '2 - Below Average'), ('3', '3 - Average'), ('4', '4 - Good'), ('5', '5 - Excellent')], max_length=1)),
                ('relevance', models.CharField(blank=True, choices=[('', 'Choose your score'), ('1', '1 - Very Poor'), ('2', '2 - Below Average'), ('3', '3 - Average'), ('4', '4 - Good'), ('5', '5 - Excellent')], max_length=1)),
                ('originality', models.CharField(blank=True, choices=[('', 'Choose your score'), ('1', '1 - Very Poor'), ('2', '2 - Below Average'), ('3', '3 - Average'), ('4', '4 - Good'), ('5', '5 - Excellent')], max_length=1)),
                ('details', models.TextField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review.Reviewer'),
        ),
    ]
