# Generated by Django 2.1.9 on 2019-07-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
