# Generated by Django 2.2.4 on 2019-08-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_filled_details'),
        ('conferences', '0010_proceedingvolume'),
        ('review', '0002_review_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('UNDEFINED', 'No decision'), ('ACCEPT', 'Accept submission'), ('REJECT', 'Reject submission')], default='UNDEFINED', max_length=10)),
                ('committed', models.BooleanField(default=False)),
                ('proc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferences.ProceedingType')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decision', to='submissions.Submission')),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferences.ProceedingVolume')),
            ],
        ),
    ]
