# Generated by Django 2.2.4 on 2019-09-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_auto_20190905_1746'),
        ('conferences', '0014_artifactdescriptor_mandatory'),
        ('review', '0004_reviewstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decision',
            new_name='DecisionOLD',
        ),
    ]
