# Generated by Django 2.2.4 on 2019-09-30 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_auto_20190905_1746'),
        ('conferences', '0014_artifactdescriptor_mandatory'),
        ('review', '0005_auto_20190925_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='decisionold',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_decision', to='submissions.Submission'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_reviews_required', models.IntegerField()),
                ('score', models.FloatField(blank=True, default=None, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='submissions.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDecisionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPT', 'Accept submission'), ('REJECT', 'Reject submission')], default='ACCEPT', max_length=6)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('allowed_proceedings', models.ManyToManyField(related_name='decision_types', to='conferences.ProceedingType')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.ReviewStage'),
        ),
    ]
