# Generated by Django 2.2.4 on 2019-10-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_redefine_scores_as_integer_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='paper',
        ),
    ]
