# Generated by Django 2.2.4 on 2019-10-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_remove_review_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='review.ReviewDecisionType')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='review.ReviewStage')),
            ],
        ),
    ]
