# Generated by Django 2.2.4 on 2019-10-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_create_new_decisions_and_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecisionOLD',
        ),
    ]
