# Generated by Django 2.2.4 on 2019-10-08 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0015_artifactdescriptor_editable'),
        ('review', '0012_delete_decisionold'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdecisiontype',
            name='conference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference'),
        ),
    ]
