# Generated by Django 2.2.4 on 2019-10-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_auto_20191008_0326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewdecisiontype',
            options={'ordering': ['conference_id', 'decision', 'description']},
        ),
    ]
